version: '3.9'
services:

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: clean-arch-temp
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest    
    ports:
      - 5672:5672
      - 15672:15672

  deposit:
    build: .
    depends_on:
      - mariadb
      - rabbitmq      
    volumes:
      - ./cmd/config.yml:/app/config.yml