app:
  name: 'app'
  version: '1.0.0'

mariadb:
  url: 127.0.0.1:3306
  user: root
  password: root
  name: clean-arch-temp

rabbitmq:
  url: amqp://localhost:5672
  consumer:
    exchange:
      name: clean-arch-temp-exchange
      type: direct
      durable: true
      auto_delete: false
      internal: false
      no_wait: false
    queue:
      name: clean-arch-temp-queue
      durable: true
      auto_delete: false
      exclusive: false
      no_wait: false
    binding_options:
      routing_key: clean-arch-temp-routing-key
      no_wait: false